[project]
name = "ksor-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.22.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ksor-worker = "ksor_worker:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
